name = "PXPTransport"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["sfhuang"]
version = "0.1.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73571a28571b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.9"
ITensors = "0.3, 0.6, 0.7, 0.8"
ITensorMPS = "0.2, 0.3"
JLD2 = "0.4, 0.5"
